# Generated by Django 5.1.1 on 2024-09-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название сериала', max_length=200, verbose_name='Заголовок страницы')),
                ('banner_img', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='Баннер главной страницы')),
                ('info_img', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='Фотография для информации о сериале')),
                ('name', models.CharField(help_text='Название фильма', max_length=90, verbose_name='Заголовок информации')),
                ('description', models.TextField(max_length=300, verbose_name='Краткий пересказ фильма')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
    ]
