# Generated by Django 5.1.1 on 2024-09-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Название сериала')),
                ('description', models.TextField(max_length=200, verbose_name='Описание сезона')),
                ('slug', models.SlugField(help_text='Заполнится автомотически', max_length=255, unique=True, verbose_name='URL')),
                ('season', models.CharField(max_length=1, verbose_name='Номер сезона')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
    ]
