# Generated by Django 5.1.1 on 2024-09-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Заполнится автоматически', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
