# Generated by Django 5.1.1 on 2024-09-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_banner',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='Фотография для главной страницы'),
        ),
    ]
