# Generated by Django 5.1.1 on 2024-09-15 08:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_category_img_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='image/')),
                ('file', models.FileField(upload_to='video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(help_text='Сезон', on_delete=django.db.models.deletion.PROTECT, related_name='Категория', to='cinema.category')),
            ],
            options={
                'verbose_name': 'Cерия',
                'verbose_name_plural': 'Серии',
            },
        ),
    ]
