# Generated by Django 5.1.1 on 2024-09-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_alter_video_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(help_text='format - № серия', max_length=8, verbose_name='Номер серии.'),
        ),
    ]
