# Generated by Django 5.1.1 on 2024-09-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type_r',
            field=models.CharField(choices=[('Нейтральная', 'Нейтральная'), ('Положительная', 'Положительная'), ('Отрицательная', 'Отрицательная')], default='Нейтральная', max_length=30, verbose_name='Статус рецензии'),
        ),
    ]
