# Generated by Django 5.1.1 on 2024-10-07 20:32

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_comment_type_r'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
