# Generated by Django 5.1.1 on 2024-10-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_alter_comment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='view',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
