# Generated by Django 5.1.1 on 2024-10-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_video_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='formatted_view',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
