# Generated by Django 5.1.1 on 2024-10-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_video_formatted_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.ImageField(blank=True, upload_to='posters/%Y/%m/%d/', verbose_name='Постер видео'),
        ),
    ]
